# EECS16A: Homework 11

# Labeling Patients Using Gene Expression Data

In [18]:
import numpy as np

In [19]:
# Part B
A = np.load('gene_data_train.npy')
b = np.load('diabetes_train.npy')
#Use Least squares to find the x vector to find the optimal parameters. 
#Calculate the coefficients using the train set
trans = A.T
sqr = trans.dot(A)
pseudoinv = (np.linalg.inv(sqr)).dot(trans)
x_hat = pseudoinv.dot(b)

In [20]:
#Test if these coefficients give the correct answer for the train set
b_new = np.sign(A.dot(x_hat))
print(b - b_new)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [22]:
# Part C
# You may find np.sign useful to generate your +/- 1 prediction vector
A_test = np.load('gene_data_test.npy')
b_test = np.load('diabetes_test.npy')
#Use x_hat to see if the model is accurate
b_calc = np.sign(A_test.dot(x_hat))

print(b_calc) #Predicted output
print(b_test) #Actual output


#if the two arrays differ at an entry, the different will either be 2 or -2, so we can calculate the test accuracy this way
test_accuracy = 1 - np.sum(np.abs(b_calc - b_test)) / (2 * 4)

print(test_accuracy)



[[1.]
 [1.]
 [1.]
 [1.]]
[[ 1.]
 [ 1.]
 [-1.]
 [ 1.]]
0.75
