# EECS16A: Homework 13

## Problem 3: Segway Tours

Run the following block of code first to get all the dependencies.

In [2]:
# %load gauss_elim.py
from gauss_elim import gauss_elim

In [3]:
from numpy import zeros, cos, sin, arange, around, hstack
from matplotlib import pyplot as plt
from matplotlib import animation
from matplotlib.patches import Rectangle
import numpy as np
from scipy.interpolate import interp1d
import scipy as sp

## Dynamics

In [6]:
# Dynamics: state to state
A = np.array([[1, 0.05, -.01, 0],
              [0, 0.22, -.17, -.01],
              [0, 0.1, 1.14, 0.10],
              [0, 1.66, 2.85, 1.14]]);
# Control to state
b = np.array([.01, .21, -.03, -0.44])
nr_states = b.shape[0]

# Initial state
state0 = np.array([-0.3853493, 6.1032227, 0.8120005, -14])

# Final (terminal state)
stateFinal = np.array([0, 0, 0, 0])

## Example Usage of Gauss_Elim

In [ ]:
#To use Gauss_Elim, first concatenate your A matrix and b vector together, as shown below:

A_test = np.array([[1, 0.05, -.01, 0],
              [0, 0.22, -.17, -.01],
              [0, 0.1, 1.14, 0.10],
              [0, 1.66, 2.85, 1.14]])

b_test = np.array([.01, .21, -.03, -0.44])

aug_matrix = np.c_[A_test, b_test]

#then you can run gauss_elim, which will give you the matrix after performing Gaussian Elimination. Each row gives you the value of the corresponding variable in the matrix.

print('Augmented matrix for aug_matrix:\n')
print(aug_matrix)

gauss_elim(aug_matrix)

#The solution would be x_1 = -0.03512281, x_2 = 0.9137542, x_3 = 0.05649046, x_4 = -1.85774542. 

Augmented matrix for aug_matrix:

[[ 1.    0.05 -0.01  0.    0.01]
 [ 0.    0.22 -0.17 -0.01  0.21]
 [ 0.    0.1   1.14  0.1  -0.03]
 [ 0.    1.66  2.85  1.14 -0.44]]


array([[ 1.        ,  0.        ,  0.        ,  0.        , -0.03512281],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  0.9137542 ],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.05649046],
       [-0.        , -0.        , -0.        ,  1.        , -1.85774542]])

In [19]:
#note: if you get a matrix where you get a row of zeros and a one at the end, this means that the system is inconsistent, and there is no solution. 
# See below for example and compare to the matrix you get above after running gauss_elim.
A_test2 = np.array([[1, 0.22, -.01, 0],
              [1, 0.22, -.17, -.01],
              [1, 0.22, 1.14, 0.10],
              [0, 0, 2.85, 1.14]])

b_test2 = np.array([.01, .21, -.03, -0.44])

aug_matrix_2 = np.c_[A_test2, b_test2]

print('Augmented matrix for aug_matrix_2:\n')
print(aug_matrix_2)

gauss_elim(aug_matrix_2)

#There is no solution since the last row is $[0, 0, 0, 0, 1], corresponding to the equation 0=1.

Augmented matrix for aug_matrix_2:

[[ 1.    0.22 -0.01  0.    0.01]
 [ 1.    0.22 -0.17 -0.01  0.21]
 [ 1.    0.22  1.14  0.1  -0.03]
 [ 0.    0.    2.85  1.14 -0.44]]


array([[1.  , 0.22, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 1.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 1.  ]])

## Part (d), (e), (f)

In [ ]:
# You may use gauss_elim to help you find the row reduced echelon form.

## Part (g)

### Preamble
This function will take care of animating the segway.

In [ ]:
# frames per second in simulation
fps = 20
# length of the segway arm/stick
stick_length = 1.

def animate_segway(t, states, controls, length):
    #Animates the segway
    
    # Set up the figure, the axis, and the plot elements we want to animate
    fig = plt.figure()
    
    # some config
    segway_width = 0.4
    segway_height = 0.2
    
    # x coordinate of the segway stick
    segwayStick_x = length * np.add(states[:, 0],sin(states[:, 2]))
    segwayStick_y = length * cos(states[:, 2])
    
    # set the limits
    xmin = min(around(states[:, 0].min() - segway_width / 2.0, 1), around(segwayStick_x.min(), 1))
    xmax = max(around(states[:, 0].max() + segway_height / 2.0, 1), around(segwayStick_y.max(), 1))
    
    # create the axes
    ax = plt.axes(xlim=(xmin-.2, xmax+.2), ylim=(-length-.1, length+.1), aspect='equal')
    
    # display the current time
    time_text = ax.text(0.05, 0.9, '', transform=ax.transAxes)
    
    # display the current control
    control_text = ax.text(0.05, 0.8, '', transform=ax.transAxes)
    
    # create rectangle for the segway
    rect = Rectangle([states[0, 0] - segway_width / 2.0, -segway_height / 2],
        segway_width, segway_height, fill=True, color='gold', ec='blue')
    ax.add_patch(rect)
    
    # blank line for the stick with o for the ends
    stick_line, = ax.plot([], [], lw=2, marker='o', markersize=6, color='blue')
    
    # vector for the control (force)
    force_vec = ax.quiver([],[],[],[],angles='xy',scale_units='xy',scale=1)

    # initialization function: plot the background of each frame
    def init():
        time_text.set_text('')
        control_text.set_text('')
        rect.set_xy((0.0, 0.0))
        stick_line.set_data([], [])
        return time_text, rect, stick_line, control_text

    # animation function: update the objects
    def animate(i):
        time_text.set_text('time = {:2.2f}'.format(t[i]))
        control_text.set_text('force = {:2.3f}'.format(controls[i]))
        rect.set_xy((states[i, 0] - segway_width / 2.0, -segway_height / 2))
        stick_line.set_data([states[i, 0], segwayStick_x[i]], [0, segwayStick_y[i]])
        return time_text, rect, stick_line, control_text

    # call the animator function
    anim = animation.FuncAnimation(fig, animate, frames=len(t), init_func=init,
            interval=1000/fps, blit=False, repeat=False)
    return anim
    # plt.show()

### Plug in your controller here

In [ ]:
controls = np.array([0,0,0,0]) # here

### Simulation

In [ ]:
# This will add an extra couple of seconds to the simulation after the input controls with no control
# the effect of this is just to show how the system will continue after the controller "stops controlling"
controls = np.append(controls,[0, 0])

# number of steps in the simulation
nr_steps = controls.shape[0]

# We now compute finer dynamics and control vectors for smoother visualization
Afine = sp.linalg.fractional_matrix_power(A,(1/fps))
Asum = np.eye(nr_states)
for i in range(1, fps):
    Asum = Asum + np.linalg.matrix_power(Afine,i)
    
bfine = np.linalg.inv(Asum).dot(b)

# We also expand the controls in the "intermediate steps" (only for visualization)
controls_final = np.outer(controls, np.ones(fps)).flatten()
controls_final = np.append(controls_final, [0])

# We compute all the states starting from x0 and using the controls
states = np.empty([fps*(nr_steps)+1, nr_states])
states[0,:] = state0;
for stepId in range(1,fps*(nr_steps)+1):
    states[stepId, :] = np.dot(Afine,states[stepId-1, :]) + controls_final[stepId-1] * bfine
    
# Now create the time vector for simulation
t = np.linspace(1/fps,nr_steps,fps*(nr_steps),endpoint=True)
t = np.append([0], t)

### Visualization

In [ ]:
%matplotlib nbagg
# %matplotlib qt
anim = animate_segway(t, states, controls_final, stick_length)
anim